spring:
  cloud:
    gateway:
      routes:
        - id: ModuleOne
          uri: http://localhost:8081
          predicates:
            - Path=/module1/**
#        - id: ModuleTwo
#          uri: http://localhost:8082
#          predicates:
#            - Path=/module2/**
